server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: airline-api-route
          uri: ${AIRLINE_API_URL:https://2ckp9swrez.us-east-1.awsapprunner.com}
          predicates:
            - Path=/v1/**
         
